services:
  api-city:
    build:
      context: ./api-city
    container_name: api-city
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      DATABASE_NAME: citydb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: "mysupersecretkeyabcdefghij1234567810"
      DATABASE_URL: jdbc:postgresql://postgres-db:5432/citydb
    networks:
      - general

  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: citydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "mysupersecretkeyabcdefghij1234567810"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - general

volumes:
  db_data:

networks:
  general: