apiVersion: v1
kind: ConfigMap
metadata:
  name: api-auth-config
data:
  DATABASE_HOST: auth-postgres-db
  DATABASE_PORT: "5432"
  DATABASE_NAME: authdb
  DATABASE_URL: jdbc:postgresql://auth-postgres-db:5432/authdb
