apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: api-auth-java:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: api-auth-config
            - secretRef:
                name: api-auth-secret
